export enum TransportCode {
  // General
  OK = 0,
  ERROR,
  CONNECTED,
  DISCONNECTED,
  NOT_IMPLEMENTED,
  COMMAND_NOT_FOUND,
  INTERFERED,
  CANT_PARSE,
  // AUTH
  AUTHENTICATED = 1000,
  AUTH_REQUIRED,
  ALREADY_AUTHENTICATED,
  INVALID_TOKEN,
  // MAP
  MOVED = 2000,
  CHANGED,
  MAP_INFO,
  LOCATION_INFO,
  ROOM_INFO,
  CHARACTER_LEAVED,
  CHARACTER_ENTERED,
  ALREADY_HERE,
  CANT_MOVE_TO_DESTINATION,
  CANT_FIND_LOCATION,
  // CHARACTER
  SELECTED_CHARACTER = 3000,
  CHARACTER_REQUIRED,
  CHARACTER_INFO,
  INVALID_USER,
  CHARACTER_NOT_FOUND,
  ALREADY_LOGGED_IN,
  // CHAT
  MESSAGE_SENT,
  MESSAGE_RECEIVED,
  INCORRECT_MESSAGE,
  WRONG_RECIEVER
}
